In [1]:
import numpy as np
print ("Hello Numpy")

a = np.array([ [[1,2,3],[4,5,6]] ,[[10,20,30], [40,50,60]]])

print(a)

Hello Numpy
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [2]:
a= np.array([[1,2], [2,3], [4,5]])
a

array([[1, 2],
       [2, 3],
       [4, 5]])

In [3]:
a= np.array([[[1,2], [2,3], [4,5]], [[1,2], [2,3], [4,5]]])

print ("number of dimension", a.ndim)
print ("number of dimension", a.shape)


number of dimension 3
number of dimension (2, 3, 2)


In [4]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(type(a))
b= a.reshape(3,4)
b

<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
help(np.char)

Help on module numpy.core.defchararray in numpy.core:

NAME
    numpy.core.defchararray

DESCRIPTION
    This module contains a set of functions for vectorized string
    operations and methods.

    .. note::
       The `chararray` class exists for backwards compatibility with
       Numarray, it is not recommended for new development. Starting from numpy
       1.4, if one needs arrays of strings, it is recommended to use arrays of
       `dtype` `object_`, `bytes_` or `str_`, and use the free functions
       in the `numpy.char` module for fast vectorized string operations.

    Some methods will only be available if the corresponding string method is
    available in your version of Python.

    The preferred alias for `defchararray` is `numpy.char`.

FUNCTIONS
    add(x1, x2)
        Return element-wise string concatenation for two arrays of str or unicode.

        Arrays `x1` and `x2` must have the same shape.

        Parameters
        ----------
        x1 : array_like of str

In [6]:
a= np.array([1,2,3,4,5,6])
b= np.array([1,2,3,4,5,6])
c= np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])

sum = np.add(a,b)
print("Sum = ",sum)
mul = np.multiply(a,b)
print("Mul = ",mul)

print("a[0]= ",a[0])
print("a[-1]= ",a[-1])

print("Slicing C[0] = ", c[0])





Sum =  [ 2  4  6  8 10 12]
Mul =  [ 1  4  9 16 25 36]
a[0]=  1
a[-1]=  6
Slicing C[0] =  [1 2 3 4 5 6]


# Learning Panda

In [3]:
import pandas as pd

In [11]:
# Series : one dimenstional
# dataframe : two dimensional array
# data types in pandas
#integer  - int 32, int 64
#float - float32, float64
#string - object

In [12]:
namesArray = ["arun", "kumar", "ashok", "ajay", "kishore"]

series  = pd.Series(namesArray)

print(series)

0       arun
1      kumar
2      ashok
3       ajay
4    kishore
dtype: object


In [14]:
index_col  = ["one", "two", "three" , "four", "five"]
series  = pd.Series(namesArray, index = index_col)
print(series) 


one         arun
two        kumar
three      ashok
four        ajay
five     kishore
dtype: object


In [15]:
sample_dict  = {"a":1, "b":2, "c":3 , "d":4, "e":5}
series = pd.Series(sample_dict)
print(series)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [22]:
print(series[1])
print(series['b'])

2
2


/var/folders/jq/dynvdnlx6flb9hdxp3pxk77w0000gn/T/ipykernel_1933/2416368466.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(series[1])


In [26]:
# display top n rows
series.head(3)
# display bottom n rows
series.tail(2)
#shape
series.shape

(5,)

In [33]:
namesArray = ["arun", "kumar", "ashok", "ajay", "kishore"]
numerArray = [100,20,34,54,55,55,55,60,70]
series = pd.Series(numerArray)
print(series.describe())



count      9.000000
mean      55.888889
std       22.177942
min       20.000000
25%       54.000000
50%       55.000000
75%       60.000000
max      100.000000
dtype: float64


In [35]:
print(series.unique())
# Count unique value
series.nunique()


[100  20  34  54  55  60  70]


7

In [38]:
pd.__version__

'2.2.2'

In [40]:
# Null value
numerArray = [100,20,34,54,55,55,55, None, None, 60,70]
series = pd.Series(numerArray)
series.isnull().sum()


2

In [41]:
series.sort_values()

1      20.0
2      34.0
3      54.0
4      55.0
5      55.0
6      55.0
9      60.0
10     70.0
0     100.0
7       NaN
8       NaN
dtype: float64

In [46]:
series.sort_values(ascending=True)

1      20.0
2      34.0
3      54.0
4      55.0
5      55.0
6      55.0
9      60.0
10     70.0
0     100.0
7       NaN
8       NaN
dtype: float64

In [9]:
sample_dict  = {"a":10, "b":20, "c":30 , "d":4, "e":55, "f":54, "g":None}
data_series = pd.Series(sample_dict)
print(data_series)

#data_gt_30 = data_series[data_series > 30]
#print(data_gt_30)

final_data = data_series.fillna(0)
print(final_data)





a    10.0
b    20.0
c    30.0
d     4.0
e    55.0
f    54.0
g     NaN
dtype: float64
a    10.0
b    20.0
c    30.0
d     4.0
e    55.0
f    54.0
g     0.0
dtype: float64


In [21]:
namesArray = ["arun", "kumar", "ashok", "ajay", "kishore", "arun", "shiju", "Manoj" , "Ina", "shiju", "shiju"]
series = pd.Series(namesArray)
print(series)
series.loc[[1,2,3]]
series[series.duplicated()]


0        arun
1       kumar
2       ashok
3        ajay
4     kishore
5        arun
6       shiju
7       Manoj
8         Ina
9       shiju
10      shiju
dtype: object


5      arun
9     shiju
10    shiju
dtype: object

In [22]:
series.str.capitalize().duplicated()


0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9      True
10     True
dtype: bool

In [23]:
#Dataframe

In [24]:
data_dict = { 
    "Name" : [ "Arun", "Ashok", "Kishor" ],
    "Age": [25,35,65],
    "Location" : [ "Chennai", "Mumbai", "Delhi"]

 }


df = pd.DataFrame(data_dict)
df

Name  Age Location
0    Arun   25  Chennai
1   Ashok   35   Mumbai
2  Kishor   65    Delhi

In [30]:
data_list = [
    ["Arun", 25, "Chennai"],
    ["Ashok",	35,	"Mumbai"],
    ["Kishor",	65,	"Delhi"]
]
data_header = ["Name", "Age", "Location"]
df = pd.DataFrame(data_list, columns=data_header)
df

Name  Age Location
0    Arun   25  Chennai
1   Ashok   35   Mumbai
2  Kishor   65    Delhi

In [40]:
fileName = "house_prices.csv"
df = pd.read_csv(fileName)


In [41]:
data_list = [
    ["Arun", 25, "Chennai"],
    ["Ashok",	35,	"Mumbai"],
    ["Kishor",	65,	"Delhi"]
]
data_header = ["Name", "Age", "Location"]
df = pd.DataFrame(data_list, columns=data_header)
df

Name  Age Location
0    Arun   25  Chennai
1   Ashok   35   Mumbai
2  Kishor   65    Delhi

In [42]:
df[['Name', 'Age']]

Name  Age
0    Arun   25
1   Ashok   35
2  Kishor   65

In [43]:
df['demo'] = df['Name'] + df['Location']
df

Name  Age Location         demo
0    Arun   25  Chennai  ArunChennai
1   Ashok   35   Mumbai  AshokMumbai
2  Kishor   65    Delhi  KishorDelhi

In [44]:
df.tail(2)

Name  Age Location         demo
1   Ashok   35   Mumbai  AshokMumbai
2  Kishor   65    Delhi  KishorDelhi

In [57]:
df = pd.read_csv("house_prices.csv")
df


Index                                              Title  \
0            0  1 BHK Ready to Occupy Flat for sale in Srushti...   
1            1  2 BHK Ready to Occupy Flat for sale in Dosti V...   
2            2  2 BHK Ready to Occupy Flat for sale in Sunrise...   
3            3        1 BHK Ready to Occupy Flat for sale Kasheli   
4            4  2 BHK Ready to Occupy Flat for sale in TenX Ha...   
...        ...                                                ...   
187526  187526  3 BHK Ready to Occupy Flat for sale in Bollywo...   
187527  187527  3 BHK Ready to Occupy Flat for sale in Sushma ...   
187528  187528  3 BHK Ready to Occupy Flat for sale in Bollywo...   
187529  187529  2 BHK Ready to Occupy Flat for sale in Friends...   
187530  187530  3 BHK Ready to Occupy Flat for sale in Affinit...   

                                              Description Amount(in rupees)  \
0       Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac    
1       One can find this stunning 2 BHK flat for sale...           98 Lac    
2       Up for immediate sale is a 2 BHK apartment in ...          1.40 Cr    
3       This beautiful 1 BHK Flat is available for sal...           25 Lac    
4       This lovely 2 BHK Flat in Pokhran Road, Thane ...          1.60 Cr    
...                                                   ...               ...   
187526  This magnificent 3 BHK Flat is available for s...           63 Lac    
187527  Have a look at this immaculate 3 BHK flat for ...           55 Lac    
187528  Gazipur, Zirakpur has an appealing 3 BHK flat ...           76 Lac    
187529  Up for immediate sale is a 2 BHK apartment in ...           30 Lac    
187530  This exquisite 3 BHK Flat is offered for sale ...          1.18 Cr    

          Price  location Carpet Area         Status         Floor  \
0        6000.0     thane    500 sqft  Ready to Move  10 out of 11   
1       13799.0     thane    473 sqft  Ready to Move   3 out of 22   
2       17500.0     thane    779 sqft  Ready to Move  10 out of 29   
3           NaN     thane    530 sqft  Ready to Move    1 out of 3   
4       18824.0     thane    635 sqft  Ready to Move  20 out of 42   
...         ...       ...         ...            ...           ...   
187526   3225.0  zirakpur         NaN  Ready to Move    2 out of 4   
187527   3274.0  zirakpur         NaN  Ready to Move    4 out of 6   
187528   4343.0  zirakpur   1250 sqft  Ready to Move    1 out of 3   
187529   4231.0  zirakpur         NaN  Ready to Move    2 out of 2   
187530   6162.0  zirakpur         NaN  Ready to Move   5 out of 13   

         Transaction  ...        facing             overlooking  \
0             Resale  ...           NaN                     NaN   
1             Resale  ...          East             Garden/Park   
2             Resale  ...          East             Garden/Park   
3             Resale  ...           NaN                     NaN   
4             Resale  ...          West  Garden/Park, Main Road   
...              ...  ...           ...                     ...   
187526  New Property  ...          East             Garden/Park   
187527        Resale  ...  North - East  Garden/Park, Main Road   
187528        Resale  ...          East  Garden/Park, Main Road   
187529        Resale  ...           NaN               Main Road   
187530        Resale  ...  North - East       Garden/Park, Pool   

                                    Society Bathroom Balcony Car Parking  \
0       Srushti Siddhi Mangal Murti Complex        1       2         NaN   
1                               Dosti Vihar        2     NaN      1 Open   
2                      Sunrise by Kalpataru        2     NaN   1 Covered   
3                                       NaN        1       1         NaN   
4               TenX Habitat Raymond Realty        2     NaN   1 Covered   
...                                     ...      ...     ...         ...   
187526                    Bollywood Esencia        3 

In [50]:
df.head

<bound method NDFrame.head of          Index                                              Title  \
0            0  1 BHK Ready to Occupy Flat for sale in Srushti...   
1            1  2 BHK Ready to Occupy Flat for sale in Dosti V...   
2            2  2 BHK Ready to Occupy Flat for sale in Sunrise...   
3            3        1 BHK Ready to Occupy Flat for sale Kasheli   
4            4  2 BHK Ready to Occupy Flat for sale in TenX Ha...   
...        ...                                                ...   
187526  187526  3 BHK Ready to Occupy Flat for sale in Bollywo...   
187527  187527  3 BHK Ready to Occupy Flat for sale in Sushma ...   
187528  187528  3 BHK Ready to Occupy Flat for sale in Bollywo...   
187529  187529  2 BHK Ready to Occupy Flat for sale in Friends...   
187530  187530  3 BHK Ready to Occupy Flat for sale in Affinit...   

                                              Description Amount(in rupees)  \
0       Bhiwandi, Thane has an attractive 1 BHK Flat f...     

In [54]:
df.head(1)

Index                                              Title  \
0      0  1 BHK Ready to Occupy Flat for sale in Srushti...   

                                         Description Amount(in rupees)  \
0  Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac    

   Price  location Carpet Area         Status         Floor Transaction  ...  \
0  6000.0    thane    500 sqft  Ready to Move  10 out of 11      Resale  ...   

  facing overlooking                              Society Bathroom Balcony  \
0    NaN         NaN  Srushti Siddhi Mangal Murti Complex        1       2   

  Car Parking Ownership Super Area Dimensions  Plot Area  
0         NaN       NaN        NaN        NaN        NaN  

[1 rows x 21 columns]

In [58]:
df.sort_values(by = 'Price')

Index                                              Title  \
154245  154245          2 BHK Ready to Occupy Flat for sale Aluva   
176399  176399    3 BHK Ready to Occupy Flat for sale Panthaghati   
165838  165838  3 BHK Ready to Occupy Flat for sale in Ashoka ...   
165311  165311     2 BHK Ready to Occupy Flat for sale Dhirenpara   
183352  183352  3 BHK Ready to Occupy Flat for sale surya apar...   
...        ...                                                ...   
187404  187404        3 BHK Ready to Occupy Flat for sale Gazipur   
187442  187442  3 BHK Ready to Occupy Flat for sale in Roseate...   
187503  187503  3 BHK Ready to Occupy Flat for sale in Aura Ho...   
187506  187506  4 BHK Ready to Occupy Flat for sale Peer Muchalla   
187513  187513  3 BHK Ready to Occupy Flat for sale in Motia C...   

                                              Description Amount(in rupees)  \
154245  Creatively planned and constructed is a 2 BHK ...           29 Lac    
176399  Panthaghati, Shimla has an appealing 3 BHK fla...          1.51 Cr    
165838  This beautiful 3 BHK Flat is available for sal...           79 Lac    
165311  This ready to move-in 2 BHK flat is available ...           48 Lac    
183352  This ready to move-in 3 BHK flat is available ...           80 Lac    
...                                                   ...               ...   
187404  This gorgeous 3 BHK Flat is available for sale...    Call for Price   
187442  Have a look at this immaculate 3 BHK flat for ...    Call for Price   
187503  Up for immediate sale is a 3 BHK apartment in ...    Call for Price   
187506  Carefully laid out in the prime location of Pe...    Call for Price   
187513  This ready to move-in 3 BHK flat is available ...    Call for Price   

        Price   location Carpet Area         Status         Floor  \
154245    0.0  ernakulam         NaN  Ready to Move  22 out of 22   
176399    0.0     shimla   1480 sqft  Ready to Move    3 out of 4   
165838    0.0   guwahati   1460 sqft  Ready to Move    1 out of 4   
165311    0.0   guwahati   1100 sqft  Ready to Move    2 out of 2   
183352    0.0   varanasi   1160 sqft  Ready to Move    2 out of 5   
...       ...        ...         ...            ...           ...   
187404    NaN   zirakpur   1450 sqft  Ready to Move    3 out of 9   
187442    NaN   zirakpur   1200 sqft  Ready to Move    2 out of 4   
187503    NaN   zirakpur    990 sqft  Ready to Move    4 out of 5   
187506    NaN   zirakpur   2500 sqft  Ready to Move    6 out of 7   
187513    NaN   zirakpur   1200 sqft  Ready to Move    3 out of 3   

         Transaction  ...        facing             overlooking  \
154245        Resale  ...           NaN                     NaN   
176399  New Property  ...         South               Main Road   
165838        Resale  ...          East               Main Road   
165311        Resale  ...           NaN                     NaN   
183352        Resale  ...          East                     NaN   
...              ...  ...           ...                     ...   
187404        Resale  ...         North             Garden/Park   
187442  New Property  ...         North             Garden/Park   
187503  New Property  ...  North - East                    Pool   
187506        Resale  ...          East  Garden/Park, Main Road   
187513        Resale  ...           NaN                     NaN   

                 Society Bathroom Balcony  Car Parking             Ownership  \
154245               NaN        2       1          NaN              Freehold   
176399               NaN        3       2  10 Covered,              Freehold   
165838  Ashoka Apartment        2       2          NaN              Freehold   
165311               NaN        2       2          NaN                   NaN   
183352               NaN        2       3          NaN              Freehold   
...                  ...      ...     ...          ...                   ...   
187404               NaN        3    

In [59]:
df.describe

<bound method NDFrame.describe of          Index                                              Title  \
0            0  1 BHK Ready to Occupy Flat for sale in Srushti...   
1            1  2 BHK Ready to Occupy Flat for sale in Dosti V...   
2            2  2 BHK Ready to Occupy Flat for sale in Sunrise...   
3            3        1 BHK Ready to Occupy Flat for sale Kasheli   
4            4  2 BHK Ready to Occupy Flat for sale in TenX Ha...   
...        ...                                                ...   
187526  187526  3 BHK Ready to Occupy Flat for sale in Bollywo...   
187527  187527  3 BHK Ready to Occupy Flat for sale in Sushma ...   
187528  187528  3 BHK Ready to Occupy Flat for sale in Bollywo...   
187529  187529  2 BHK Ready to Occupy Flat for sale in Friends...   
187530  187530  3 BHK Ready to Occupy Flat for sale in Affinit...   

                                              Description Amount(in rupees)  \
0       Bhiwandi, Thane has an attractive 1 BHK Flat f... 

In [61]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [63]:
df = pd.date_range(start='2023-01-01', end= '2023-01-10', freq= 'D')
df

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10'],
              dtype='datetime64[ns]', freq='D')

In [75]:
date = { 'date' : ['2023-01-01', '2023-01-15', '2023-03-15', '2023-03-20'] }
df = pd.DataFrame(date) 
df

date
0  2023-01-01
1  2023-01-15
2  2023-03-15
3  2023-03-20

In [78]:
df['date'] = pd.to_datetime(df['date'])
df

date
0 2023-01-01
1 2023-01-15
2 2023-03-15
3 2023-03-20

In [87]:
df["next_Day"] = df['date'] + pd.Timedelta(days = 1)
df["Year"] = pd.DatetimeIndex(df['date']).year
df["Month"] = pd.DatetimeIndex(df['date'] ).month
df["Day"] = pd.DatetimeIndex(df['date'] ).day
df

date   next_Day  Year  Month  Day
0 2023-01-01 2023-01-02  2023      1    1
1 2023-01-15 2023-01-16  2023      1   15
2 2023-03-15 2023-03-16  2023      3   15
3 2023-03-20 2023-03-21  2023      3   20

In [88]:
data_list = [
    ["Arun", 25, "Chennai"],
    ["Ashok",	35,	"Mumbai"],
    ["Kishor",	65,	"Delhi"]
]
data_header = ["Name", "Age", "Location"]
df = pd.DataFrame(data_list, columns=data_header)
df

Name  Age Location
0    Arun   25  Chennai
1   Ashok   35   Mumbai
2  Kishor   65    Delhi

In [89]:
df['location_lower'] = df['Location'].str.lower()
df

Name  Age Location location_lower
0    Arun   25  Chennai        chennai
1   Ashok   35   Mumbai         mumbai
2  Kishor   65    Delhi          delhi

In [90]:
for index, row in df.iterrows
    

SyntaxError: expected ':' (2895678634.py, line 1)

In [92]:
df = pd.read_csv("house_prices.csv")
df.head(1)

Index                                              Title  \
0      0  1 BHK Ready to Occupy Flat for sale in Srushti...   

                                         Description Amount(in rupees)  \
0  Bhiwandi, Thane has an attractive 1 BHK Flat f...           42 Lac    

    Price location Carpet Area         Status         Floor Transaction  ...  \
0  6000.0    thane    500 sqft  Ready to Move  10 out of 11      Resale  ...   

  facing overlooking                              Society Bathroom Balcony  \
0    NaN         NaN  Srushti Siddhi Mangal Murti Complex        1       2   

  Car Parking Ownership Super Area Dimensions  Plot Area  
0         NaN       NaN        NaN        NaN        NaN  

[1 rows x 21 columns]

In [103]:
import pandasql as sqldf
db_filter = sqldf("select * fron df")
#db_filter.head()

TypeError: 'module' object is not callable