In [1]:
import numpy as np
print ("Hello Numpy")

a = np.array([ [[1,2,3],[4,5,6]] ,[[10,20,30], [40,50,60]]])

print(a)

Hello Numpy
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [2]:
a= np.array([[1,2], [2,3], [4,5]])
a

array([[1, 2],
       [2, 3],
       [4, 5]])

In [3]:
a= np.array([[[1,2], [2,3], [4,5]], [[1,2], [2,3], [4,5]]])

print ("number of dimension", a.ndim)
print ("number of dimension", a.shape)


number of dimension 3
number of dimension (2, 3, 2)


In [4]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(type(a))
b= a.reshape(3,4)
b

<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
help(np.char)

Help on module numpy.core.defchararray in numpy.core:

NAME
    numpy.core.defchararray

DESCRIPTION
    This module contains a set of functions for vectorized string
    operations and methods.

    .. note::
       The `chararray` class exists for backwards compatibility with
       Numarray, it is not recommended for new development. Starting from numpy
       1.4, if one needs arrays of strings, it is recommended to use arrays of
       `dtype` `object_`, `bytes_` or `str_`, and use the free functions
       in the `numpy.char` module for fast vectorized string operations.

    Some methods will only be available if the corresponding string method is
    available in your version of Python.

    The preferred alias for `defchararray` is `numpy.char`.

FUNCTIONS
    add(x1, x2)
        Return element-wise string concatenation for two arrays of str or unicode.

        Arrays `x1` and `x2` must have the same shape.

        Parameters
        ----------
        x1 : array_like of str

In [6]:
a= np.array([1,2,3,4,5,6])
b= np.array([1,2,3,4,5,6])
c= np.array([[1,2,3,4,5,6], [1,2,3,4,5,6]])

sum = np.add(a,b)
print("Sum = ",sum)
mul = np.multiply(a,b)
print("Mul = ",mul)

print("a[0]= ",a[0])
print("a[-1]= ",a[-1])

print("Slicing C[0] = ", c[0])





Sum =  [ 2  4  6  8 10 12]
Mul =  [ 1  4  9 16 25 36]
a[0]=  1
a[-1]=  6
Slicing C[0] =  [1 2 3 4 5 6]


# Learning Panda

In [10]:
import pandas as pd

In [11]:
# Series : one dimenstional
# dataframe : two dimensional array
# data types in pandas
#integer  - int 32, int 64
#float - float32, float64
#string - object

In [12]:
namesArray = ["arun", "kumar", "ashok", "ajay", "kishore"]

series  = pd.Series(namesArray)

print(series)

0       arun
1      kumar
2      ashok
3       ajay
4    kishore
dtype: object


In [14]:
index_col  = ["one", "two", "three" , "four", "five"]
series  = pd.Series(namesArray, index = index_col)
print(series) 


one         arun
two        kumar
three      ashok
four        ajay
five     kishore
dtype: object


In [ ]:
sample_dict  = {"a":1, "b":2, "c":3 , "d":4, "e":5}

